E-Ecommerce que vende produtos eletrônicos.

TABELA PESSOA
ID_PESSOA - PRIMARY KEY
NOME      - VARCHAR(50)
DATA_NASC - DATE 

TABELA ENDERECO_PESSOA
ID_ENDERECO  - PRIMARY KEY AUTO_INCREMENT 
ID_PESSOA    - FOREIGN KEY NOT NULL
RUA          - VARCHAR(50)
BAIRRO       - VARCHAR(50)
COMPLEMENTO  - VARCHAR(50)
ESTADO       - VARCHAR(3)
CIDADE       - TEXT
PAIS         - VARCHAR(3)
CEP          - VARCHAR(9)

TABELA TELEFONE_PESSOA
ID_TELEFONE - PRIMARY KEY AUTO_INCREMENT
ID_PESSOA   - FOREIGN KEY NOT NULL
TELEFONE    - VARCHAR(20)

TABELA VENDEDOR
ID_VENDEDOR - PRIMARY KEY AUTO_INCREMENT UNIQUE
ID_PESSOA   - FOREIGN KEY NOT NULL

Tabela CLIENTE
ID_CLIENTE - PRIMARY KEY AUTO_INCREMENT UNIQUE
ID_PESSOA  - FOREIGN KEY  NOT NULL

TABELA PRODUTO
ID_PRODUTO   - PRIMARY KEY AUTO_INCREMENT
ID_CATEGORIA - FOREIGN KEY NOT NULL
NOME_PRODUTO - VARCHAR(50) NOT NULL
PRECO        - DECIMAL(10,2) NOT NULL

TABELA CATEGORIA
ID_CATEGORIA - PRIMARY KEY AUTO_INCREMENT
NOME         - VARCHAR(50)

TABELA PEDIDO
ID_PEDIDO   - PRIMARY KEY AUTO_INCREMENT
ID_CLIENTE  - FOREIGN KEY NOT NULL
ID_VENDEDOR - FOREIGN KEY NOT NULL
DATA_PED    - DATE


TABELA ITEM_PEDIDO
ID_ITEM       - PRIMARY KEY AUTO_INCREMENT
ID_PRODUTO    - FOREIGN KEY NOT NULL
ID_PEDIDO     - FOREIGN KEY NOT NULL
QUANTIDADE    - INT
PRECO_UNIDADE - DECIMAL(10,2)

